[package]
name = "freeverb-wasm"
version = "0.0.1"
authors = ["Ian Hobson <ian.r.hobson@gmail.com>"]
edition = "2018"

[dependencies]
freeverb = { path = "../freeverb" }
wasm-bindgen = "0.2.28"

[lib]
crate-type = ["cdylib"]
